export enum EventStatus {
    UPCOMING = 'UPCOMING',
    REGISTRATION = 'REGISTRATION',
    ONGOING = 'ONGOING',
    CONCLUDED = 'CONCLUDED',
    CANCELLED = 'CANCELLED',
    FINALIZED = 'FINALIZED',
}
